server:
    port: 8080
    servlet:
        context-path: /identity


spring:
    datasource:
        url: "jdbc:mysql://localhost:3306/identity_service"
        username: root
        password:
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true

jwt:
    signerKey: "oRHwBBoR7tASJ77mkMv2WMrZxTlGZj/7sVl5tK4ga7oSteoyhyh1QOLUvJwYQUS0"

logging:
    level:
        org.springframework.web: DEBUG
        org.springframework.security: DEBUG
        org.springframework.boot.autoconfigure: INFO
